### ISSUE TITLE
Orientation changing cause crash

### ISSUE THREAD

**Issue by walkingice** [walkingice/Progressbar#2]

**Comment by walkingice** [comment]
```
Process: bar.foo.julian.dummy, PID: 15129
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.postDelayed(java.lang.Runnable, long)' on a null object 
    at org.mozilla.gecko.widget.AnimatedProgressBar.animateClosing(AnimatedProgressBar.java:129)
    at org.mozilla.gecko.widget.AnimatedProgressBar.setVisibility(AnimatedProgressBar.java:114)
    at bar.foo.julian.dummy.MainActivity$MyHandler.handleMessage(MainActivity.java:156)
    at android.os.Handler.dispatchMessage(Handler.java:102)
```

It seems this bug is fixed in #4
